name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - px25  # Add additional branches you want to deploy

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: github.repository == 'yoshikiohshima/renkon-pad'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build main branch
        run: |
          mkdir -p output/main
          cp index.html pad.js preact.standalone.module.js renkon-pad.json renkon-web.js stable-stringify.js cf.json llama.json output

      - name: Checkout px25 branch
        uses: actions/checkout@v4
        with:
          ref: px25
          path: px25_temp  # Checkout px25 branch into a temporary directory

      - name: Copy px25 branch to output
        run: |
          mkdir -p output/px25
          cp px25_temp/index.html px25_temp/pad.js px25_temp/preact.standalone.module.js px25_temp/renkon-pad.json px25_temp/renkon-web.js px25_temp/stable-stringify.js px25_temp/cf.json px25_temp/llama.json output/px25

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
