name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - px25  # Add additional branches you want to deploy

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build main branch
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p output/main
          # Run your build steps here (e.g., npm run build)
          cp index.html pad.js preact.standalone.module.js renkon-pad.json renkon-web.js stable-stringify.js output/main

      - name: Checkout px25 branch
        if: github.ref == 'refs/heads/px25'
        uses: actions/checkout@v4
        with:
          ref: px25

      - name: Build px25 branch
        if: github.ref == 'refs/heads/px25'
        run: |
          mkdir -p output/px25
          # Run your build steps here (e.g., npm run build)
          cp index.html pad.js preact.standalone.module.js renkon-pad.json renkon-web.js stable-stringify.js output/px25

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
